main:
  # - name: 简介
  #   url: '#about'
  #   weight: 1
  - name: UE4
    url: /categories/ue4
    weight: 1
  - name: UE5
    url: /categories/ue5
    weight: 2
  - name: 材质
    url: /categories/材质
    weight: 2
  - name: 系列
    url: /series/
    weight: 3
  - name: Tags
    url: /tags/
    weight: 4
  # - name: Docs
  #   url: /docs/
  #   weight: 3